export const strategyRegistryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_strategyNFT", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addAllowedProtocol",
    inputs: [{ name: "protocol", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "encodeStrategy",
    inputs: [
      {
        name: "steps",
        type: "tuple[]",
        internalType: "struct IStrategyRegistry.Step[]",
        components: [
          { name: "actionType", type: "uint8", internalType: "uint8" },
          { name: "protocol", type: "address", internalType: "address" },
          { name: "tokenIn", type: "address", internalType: "address" },
          { name: "tokenOut", type: "address", internalType: "address" },
          { name: "params", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getStep",
    inputs: [
      { name: "tokenId", type: "uint256", internalType: "uint256" },
      { name: "stepIndex", type: "uint8", internalType: "uint8" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IStrategyRegistry.Step",
        components: [
          { name: "actionType", type: "uint8", internalType: "uint8" },
          { name: "protocol", type: "address", internalType: "address" },
          { name: "tokenIn", type: "address", internalType: "address" },
          { name: "tokenOut", type: "address", internalType: "address" },
          { name: "params", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStepCount",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStrategyConfig",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IStrategyRegistry.StrategyConfig",
        components: [
          { name: "tokenId", type: "uint256", internalType: "uint256" },
          { name: "protocols", type: "address[]", internalType: "address[]" },
          { name: "stepCount", type: "uint8", internalType: "uint8" },
          { name: "minDeposit", type: "uint256", internalType: "uint256" },
          { name: "maxDeposit", type: "uint256", internalType: "uint256" },
          { name: "isPublic", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStrategyProtocols",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStrategySteps",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct IStrategyRegistry.Step[]",
        components: [
          { name: "actionType", type: "uint8", internalType: "uint8" },
          { name: "protocol", type: "address", internalType: "address" },
          { name: "tokenIn", type: "address", internalType: "address" },
          { name: "tokenOut", type: "address", internalType: "address" },
          { name: "params", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isProtocolAllowed",
    inputs: [{ name: "protocol", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingOwner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerStrategy",
    inputs: [
      { name: "tokenId", type: "uint256", internalType: "uint256" },
      { name: "strategyData", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeAllowedProtocol",
    inputs: [{ name: "protocol", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "strategyNFT",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateStrategyConfig",
    inputs: [
      { name: "tokenId", type: "uint256", internalType: "uint256" },
      { name: "minDeposit", type: "uint256", internalType: "uint256" },
      { name: "maxDeposit", type: "uint256", internalType: "uint256" },
      { name: "isPublic", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "validateStrategy",
    inputs: [{ name: "strategyData", type: "bytes", internalType: "bytes" }],
    outputs: [
      { name: "valid", type: "bool", internalType: "bool" },
      { name: "reason", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "OwnershipTransferStarted",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolAllowed",
    inputs: [
      {
        name: "protocol",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolRemoved",
    inputs: [
      {
        name: "protocol",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StrategyRegistered",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "protocols",
        type: "address[]",
        indexed: false,
        internalType: "address[]",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "InvalidEncoding", inputs: [] },
  { type: "error", name: "InvalidStepData", inputs: [] },
  { type: "error", name: "InvalidStrategy", inputs: [] },
  { type: "error", name: "OnlyNFTContract", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ProtocolNotAllowed", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "StrategyNotFound", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;
export type StrategyRegistryAbi = typeof strategyRegistryAbi;
